import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BookOpen, Radio, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SeoSection } from "@/components/SeoSection";
import { SiteImage } from "@/components/SiteImage";
import observationImage from "@/assets/mobility-real.jpg.asset.json";

export const Route = createFileRoute("/aktuelles")({ head: () => ({ meta: [
  { title: "Aktuelles zu Mobilität & Energie | planem" }, { name: "description", content: "Künftig: verständlich eingeordnete Fachinformationen zu Mobilität, Energieeffizienz, Förderung und Regulierung." },
  { property: "og:title", content: "Aktuelles | planem" }, { property: "og:description", content: "Verlässliche Fachinformationen, verständlich eingeordnet." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }
] }), component: NewsPage });
function NewsPage() { return <><section className="bg-ink py-20 text-ink-foreground md:py-28"><div className="site-container grid gap-10 md:grid-cols-[1fr_2fr]"><p className="eyebrow !text-brand-light">Aktuelles</p><div><h1 className="max-w-4xl text-5xl font-extralight leading-[1.05] md:text-7xl">Evidenz einordnen. Methodik erkennen.</h1><p className="mt-7 max-w-2xl text-lg font-light leading-8 text-ink-muted">Hier entsteht ein sorgfältig kuratierter Überblick zu Mobilität, Energieeffizienz, Förderung und regulatorischen Entwicklungen.</p></div></div></section><section className="py-20 md:py-28"><div className="site-container"><div className="grid gap-10 lg:grid-cols-[1fr_1.4fr]"><div><span className="inline-flex border border-primary px-3 py-1 text-xs font-semibold uppercase tracking-[.16em] text-primary">In Vorbereitung</span><h2 className="mt-6 text-4xl font-light">Keine schnelle Schlagzeile. Sondern belastbare Orientierung.</h2></div><div className="grid gap-px bg-border sm:grid-cols-3">{[{icon:Users,label:"Stimmen aus Wissenschaft und Praxis"},{icon:Radio,label:"Ausgewählte journalistische Quellen"},{icon:BookOpen,label:"Fachliteratur verständlich aufbereitet"}].map(({icon:Icon,label})=><div key={label} className="bg-background p-6"><Icon className="size-6 text-primary"/><p className="mt-10 text-sm font-medium leading-6">{label}</p></div>)}</div></div><div className="mt-16 grid gap-8 lg:grid-cols-[1.4fr_1fr] lg:items-center"><SiteImage imageKey="aktuelles.observation" fallback={observationImage.url} alt="Baustellensituation mit markierter Radverkehrsführung in Münster" loading="lazy" width={1400} height={1000} className="aspect-[7/4] w-full object-cover" /><figcaption className="text-lg font-light leading-8 text-muted-foreground">So sieht es derzeit aus: Baustelle, eingeschränkte Radführung, unattraktive Infrastruktur. Genau hier setzt Planung an – aus dem Ist-Zustand entsteht ein Konzept, das besser fahrbar, sicherer und werterhöhend ist.</figcaption></div><div className="mt-16 border-y border-border py-10"><p className="max-w-3xl text-lg leading-8 text-muted-foreground">Die spätere Auswahl und Aufbereitung soll transparent auf Quellen verweisen und Inhalte von anerkannten Fachpersonen, öffentlich-rechtlichen Wissensformaten, seriösen Medien und Fachliteratur nachvollziehbar zusammenführen. Die technische KI-Unterstützung folgt in einem späteren Schritt.</p></div></div></section><section className="bg-secondary py-16"><div className="site-container flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="eyebrow">Bis dahin</p><h2 className="mt-3 text-3xl font-light">Sie haben eine konkrete Fachfrage?</h2></div><Button asChild><Link to="/kontakt">Direkt anfragen <ArrowRight/></Link></Button></div></section><SeoSection /></>; }
