import { createFileRoute, Link } from "@tanstack/react-router";
import { useState, type FormEvent, type ReactNode } from "react";
import { CheckCircle2, Mail, MapPin, Send } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";

export const Route = createFileRoute("/kontakt")({ head: () => ({ meta: [
  { title: "Kontakt & Termin | planem Münster" }, { name: "description", content: "Termin, Angebot oder allgemeine Anfrage an planem | Ingenieur Marcel Stüer in Münster." },
  { property: "og:title", content: "Kontakt | planem" }, { property: "og:description", content: "Sprechen Sie mit planem über Ihr Mobilitäts- oder Energieprojekt." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }
] }), component: ContactPage });

function ContactPage() { const [status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle");
  async function submit(event:FormEvent<HTMLFormElement>){ event.preventDefault(); setStatus("sending"); const data=new FormData(event.currentTarget); const payload={request_type:String(data.get("request_type")),name:String(data.get("name")).trim(),email:String(data.get("email")).trim(),phone:String(data.get("phone")).trim()||null,organization:String(data.get("organization")).trim()||null,message:String(data.get("message")).trim(),privacy_accepted:data.get("privacy_accepted")==="on"}; const {error}=await supabase.from("contact_requests").insert(payload); if(error){console.error(error);setStatus("error");return;} setStatus("success"); event.currentTarget.reset(); }
  return <section className="py-16 md:py-24"><div className="site-container"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><aside><p className="eyebrow">Kontakt</p><h1 className="mt-5 text-5xl font-extralight leading-tight md:text-6xl">Erzählen Sie von Ihrem Vorhaben.</h1><p className="mt-6 max-w-md text-lg font-light leading-8 text-muted-foreground">Ob erste Einschätzung, konkretes Angebot oder Terminwunsch: Ihre Anfrage landet direkt bei planem.</p><div className="mt-10 space-y-5 border-t border-border pt-7 text-sm"><a href="mailto:info@planem.de" className="flex items-center gap-3 font-medium hover:text-primary"><Mail className="size-5 text-primary"/>info@planem.de</a><div className="flex items-start gap-3"><MapPin className="mt-0.5 size-5 text-primary"/><address className="not-italic leading-6">planem | Ingenieur Marcel Stüer<br/>Bohlweg 21<br/>48147 Münster</address></div></div></aside>
  <div className="border border-border bg-card p-6 md:p-10">{status==="success" ? <div className="flex min-h-[440px] flex-col items-start justify-center"><CheckCircle2 className="size-12 text-primary"/><h2 className="mt-6 text-3xl font-light">Vielen Dank für Ihre Anfrage.</h2><p className="mt-4 max-w-md leading-7 text-muted-foreground">Ihre Nachricht wurde sicher übermittelt. planem meldet sich so bald wie möglich bei Ihnen.</p><Button className="mt-7" variant="outline" onClick={()=>setStatus("idle")}>Weitere Anfrage senden</Button></div> : <form onSubmit={submit} className="space-y-6"><fieldset><legend className="mb-3 text-sm font-medium">Worum geht es?</legend><div className="grid gap-2 sm:grid-cols-3">{[["termin","Termin"],["angebot","Angebot"],["allgemein","Allgemeine Anfrage"]].map(([value,label])=><label key={value} className="cursor-pointer"><input className="peer sr-only" type="radio" name="request_type" value={value} defaultChecked={value==="termin"}/><span className="flex min-h-11 items-center justify-center border border-input px-3 text-center text-sm peer-checked:border-primary peer-checked:bg-secondary peer-checked:text-primary">{label}</span></label>)}</div></fieldset><div className="grid gap-5 sm:grid-cols-2"><Field id="name" label="Name *"><Input id="name" name="name" required minLength={2} autoComplete="name"/></Field><Field id="organization" label="Unternehmen / Organisation"><Input id="organization" name="organization" autoComplete="organization"/></Field><Field id="email" label="E-Mail *"><Input id="email" name="email" type="email" required autoComplete="email"/></Field><Field id="phone" label="Telefon"><Input id="phone" name="phone" type="tel" autoComplete="tel"/></Field></div><Field id="message" label="Ihre Nachricht *"><Textarea id="message" name="message" required minLength={10} maxLength={5000} className="min-h-40" placeholder="Worum geht es bei Ihrem Vorhaben?"/></Field><label className="flex items-start gap-3 text-sm leading-6 text-muted-foreground"><input type="checkbox" name="privacy_accepted" required className="mt-1 size-4 accent-primary"/><span>Ich stimme der Verarbeitung meiner Angaben zur Bearbeitung meiner Anfrage zu. Weitere Informationen stehen in der <Link to="/datenschutz" className="font-medium text-foreground underline underline-offset-4">Datenschutzerklärung</Link>.</span></label>{status==="error"&&<p role="alert" className="text-sm text-destructive">Die Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es erneut oder schreiben Sie an info@planem.de.</p>}<Button type="submit" size="lg" disabled={status==="sending"}>{status==="sending"?"Wird gesendet …":"Anfrage senden"}<Send/></Button></form>}</div></div></div></section>; }
function Field({id,label,children}:{id:string;label:string;children:ReactNode}){return <div className="space-y-2"><Label htmlFor={id}>{label}</Label>{children}</div>}
