import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Award, Compass, GraduationCap, MapPin } from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/ueber-planem")({ head: () => ({ meta: [
  { title: "Über planem | Ingenieur Marcel Stüer" }, { name: "description", content: "Qualifikation, Erfahrung und Haltung von planem – Ingenieurbüro für Mobilität und Energieeffizienz aus Münster." },
  { property: "og:title", content: "Über planem | Marcel Stüer" }, { property: "og:description", content: "Technische Kompetenz, internationale Perspektive und regionale Nähe." }, { property: "og:type", content: "profile" }, { name: "twitter:card", content: "summary_large_image" }
] }), component: AboutPage });
function AboutPage() { const facts=[{icon:GraduationCap,title:"Technisches Fundament",text:"Master of Engineering im Technischen Management, Bachelor of Science in Umwelttechnik und Ausbildung zum Technischen Zeichner."},{icon:Award,title:"Zertifizierte Expertise",text:"Seit 2016 BAFA- und KfW-zertifizierter Energieberater für Nichtwohngebäude sowie IHK-zertifizierter Mobilitätsmanager."},{icon:Compass,title:"Internationale Perspektive",text:"Berufliche Erfahrungen aus den USA, Japan und den Niederlanden erweitern den Blick auf bewährte Lösungen."},{icon:MapPin,title:"Regional erreichbar",text:"Persönliche Beratung in Münster und im Münsterland, in Ostwestfalen sowie im Osnabrücker Land."}]; return <><section className="py-20 md:py-28"><div className="site-container grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Über planem</p><p className="mt-7 text-xl font-light leading-8 text-muted-foreground">planem steht für pragmatische Ingenieurarbeit mit Blick über den eigenen Fachbereich hinaus.</p></div><div><h1 className="text-5xl font-extralight leading-[1.05] md:text-7xl">Technische Tiefe.<br/><span className="text-primary">Offener Blick.</span></h1><div className="mt-10 grid gap-6 text-base leading-7 text-muted-foreground md:grid-cols-2"><p>Gegründet von Marcel Stüer verbindet planem die Themen Mobilität, Energieeffizienz und ökologische Nachhaltigkeit in einem Planungs- und Beratungsbüro.</p><p>Das Ziel: regulatorische und technische Anforderungen so aufzubereiten, dass daraus klare, wirtschaftlich tragfähige und zukunftsfeste Entscheidungen entstehen.</p></div></div></div></section><section className="bg-secondary py-20 md:py-24"><div className="site-container"><div className="grid gap-px bg-border md:grid-cols-2">{facts.map(({icon:Icon,title,text})=><article key={title} className="bg-secondary p-7 md:p-10"><Icon className="size-7 text-primary"/><h2 className="mt-8 text-2xl font-light">{title}</h2><p className="mt-4 leading-7 text-muted-foreground">{text}</p></article>)}</div></div></section><section className="py-20 md:py-28"><div className="site-container grid gap-10 md:grid-cols-[1fr_1.5fr]"><p className="eyebrow">Arbeitsweise</p><div><blockquote className="text-3xl font-light leading-tight md:text-5xl">„Gute Beratung beginnt mit den richtigen Fragen – und endet mit einer Lösung, die wirklich umgesetzt werden kann.“</blockquote><p className="mt-8 text-muted-foreground">Marcel Stüer, Gründer von planem</p><Button asChild className="mt-9"><Link to="/kontakt">Persönlich kennenlernen <ArrowRight/></Link></Button></div></div></section></>; }
