/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AktuellesRouteImport } from './routes/aktuelles'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as UeberPlanemRouteImport } from './routes/ueber-planem'
import { Route as AktuellesIndexRouteImport } from './routes/aktuelles.index'
import { Route as LeistungenIndexRouteImport } from './routes/leistungen.index'
import { Route as LeistungenEnergieberatungRouteImport } from './routes/leistungen.energieberatung'
import { Route as LeistungenMobilitaetskonzepteRouteImport } from './routes/leistungen.mobilitaetskonzepte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AktuellesRoute = AktuellesRouteImport.update({
  id: '/aktuelles',
  path: '/aktuelles',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberPlanemRoute = UeberPlanemRouteImport.update({
  id: '/ueber-planem',
  path: '/ueber-planem',
  getParentRoute: () => rootRouteImport,
} as any)
const AktuellesIndexRoute = AktuellesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AktuellesRoute,
} as any)
const LeistungenIndexRoute = LeistungenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeistungenRoute,
} as any)
const LeistungenEnergieberatungRoute =
  LeistungenEnergieberatungRouteImport.update({
    id: '/energieberatung',
    path: '/energieberatung',
    getParentRoute: () => LeistungenRoute,
  } as any)
const LeistungenMobilitaetskonzepteRoute =
  LeistungenMobilitaetskonzepteRouteImport.update({
    id: '/mobilitaetskonzepte',
    path: '/mobilitaetskonzepte',
    getParentRoute: () => LeistungenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aktuelles': typeof AktuellesRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/ueber-planem': typeof UeberPlanemRoute
  '/leistungen/energieberatung': typeof LeistungenEnergieberatungRoute
  '/leistungen/mobilitaetskonzepte': typeof LeistungenMobilitaetskonzepteRoute
  '/aktuelles/': typeof AktuellesIndexRoute
  '/leistungen/': typeof LeistungenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/ueber-planem': typeof UeberPlanemRoute
  '/leistungen/energieberatung': typeof LeistungenEnergieberatungRoute
  '/leistungen/mobilitaetskonzepte': typeof LeistungenMobilitaetskonzepteRoute
  '/aktuelles': typeof AktuellesIndexRoute
  '/leistungen': typeof LeistungenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aktuelles': typeof AktuellesRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/leistungen': typeof LeistungenRouteWithChildren
  '/ueber-planem': typeof UeberPlanemRoute
  '/leistungen/energieberatung': typeof LeistungenEnergieberatungRoute
  '/leistungen/mobilitaetskonzepte': typeof LeistungenMobilitaetskonzepteRoute
  '/aktuelles/': typeof AktuellesIndexRoute
  '/leistungen/': typeof LeistungenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aktuelles'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/ueber-planem'
    | '/leistungen/energieberatung'
    | '/leistungen/mobilitaetskonzepte'
    | '/aktuelles/'
    | '/leistungen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/ueber-planem'
    | '/leistungen/energieberatung'
    | '/leistungen/mobilitaetskonzepte'
    | '/aktuelles'
    | '/leistungen'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aktuelles'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/leistungen'
    | '/ueber-planem'
    | '/leistungen/energieberatung'
    | '/leistungen/mobilitaetskonzepte'
    | '/aktuelles/'
    | '/leistungen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AktuellesRoute: typeof AktuellesRouteWithChildren
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  LeistungenRoute: typeof LeistungenRouteWithChildren
  UeberPlanemRoute: typeof UeberPlanemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktuelles': {
      id: '/aktuelles'
      path: '/aktuelles'
      fullPath: '/aktuelles'
      preLoaderRoute: typeof AktuellesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-planem': {
      id: '/ueber-planem'
      path: '/ueber-planem'
      fullPath: '/ueber-planem'
      preLoaderRoute: typeof UeberPlanemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktuelles/': {
      id: '/aktuelles/'
      path: '/'
      fullPath: '/aktuelles/'
      preLoaderRoute: typeof AktuellesIndexRouteImport
      parentRoute: typeof AktuellesRoute
    }
    '/leistungen/': {
      id: '/leistungen/'
      path: '/'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof LeistungenIndexRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/leistungen/energieberatung': {
      id: '/leistungen/energieberatung'
      path: '/energieberatung'
      fullPath: '/leistungen/energieberatung'
      preLoaderRoute: typeof LeistungenEnergieberatungRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/leistungen/mobilitaetskonzepte': {
      id: '/leistungen/mobilitaetskonzepte'
      path: '/mobilitaetskonzepte'
      fullPath: '/leistungen/mobilitaetskonzepte'
      preLoaderRoute: typeof LeistungenMobilitaetskonzepteRouteImport
      parentRoute: typeof LeistungenRoute
    }
  }
}

interface AktuellesRouteChildren {
  AktuellesIndexRoute: typeof AktuellesIndexRoute
}

const AktuellesRouteChildren: AktuellesRouteChildren = {
  AktuellesIndexRoute: AktuellesIndexRoute,
}

const AktuellesRouteWithChildren = AktuellesRoute._addFileChildren(
  AktuellesRouteChildren,
)

interface LeistungenRouteChildren {
  LeistungenEnergieberatungRoute: typeof LeistungenEnergieberatungRoute
  LeistungenMobilitaetskonzepteRoute: typeof LeistungenMobilitaetskonzepteRoute
  LeistungenIndexRoute: typeof LeistungenIndexRoute
}

const LeistungenRouteChildren: LeistungenRouteChildren = {
  LeistungenEnergieberatungRoute: LeistungenEnergieberatungRoute,
  LeistungenMobilitaetskonzepteRoute: LeistungenMobilitaetskonzepteRoute,
  LeistungenIndexRoute: LeistungenIndexRoute,
}

const LeistungenRouteWithChildren = LeistungenRoute._addFileChildren(
  LeistungenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AktuellesRoute: AktuellesRouteWithChildren,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRouteWithChildren,
  UeberPlanemRoute: UeberPlanemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
