/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AktuellesRouteImport } from './routes/aktuelles'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as UeberPlanemRouteImport } from './routes/ueber-planem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AktuellesRoute = AktuellesRouteImport.update({
  id: '/aktuelles',
  path: '/aktuelles',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberPlanemRoute = UeberPlanemRouteImport.update({
  id: '/ueber-planem',
  path: '/ueber-planem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktuelles': typeof AktuellesRoute
  '/leistungen': typeof LeistungenRoute
  '/ueber-planem': typeof UeberPlanemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktuelles': typeof AktuellesRoute
  '/leistungen': typeof LeistungenRoute
  '/ueber-planem': typeof UeberPlanemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktuelles': typeof AktuellesRoute
  '/leistungen': typeof LeistungenRoute
  '/ueber-planem': typeof UeberPlanemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aktuelles' | '/leistungen' | '/ueber-planem'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aktuelles' | '/leistungen' | '/ueber-planem'
  id: '__root__' | '/' | '/aktuelles' | '/leistungen' | '/ueber-planem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktuellesRoute: typeof AktuellesRoute
  LeistungenRoute: typeof LeistungenRoute
  UeberPlanemRoute: typeof UeberPlanemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktuelles': {
      id: '/aktuelles'
      path: '/aktuelles'
      fullPath: '/aktuelles'
      preLoaderRoute: typeof AktuellesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-planem': {
      id: '/ueber-planem'
      path: '/ueber-planem'
      fullPath: '/ueber-planem'
      preLoaderRoute: typeof UeberPlanemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktuellesRoute: AktuellesRoute,
  LeistungenRoute: LeistungenRoute,
  UeberPlanemRoute: UeberPlanemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
